package supermercadoconcorrencia;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;

public class SupermercadoGUI extends javax.swing.JFrame {

    public static boolean violarExclusaoMutua = false;
    public static boolean inanicao = false;
    public static boolean deadlock = false;

    public SupermercadoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtQuantCaixa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtQuantClientes = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbDeadlock = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        txtTempoFuncionamento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbInanicao = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtQuantTroco = new javax.swing.JTextField();
        txtChanceTroco = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTempoCompra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btbIniciar = new javax.swing.JButton();
        cbViolarExclusaoMutua = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Supermercado com concorrência");

        jLabel2.setText("Um supermercado possui alguns caixas que devem atender vários clientes, mas em cada caixa, só um cliente pode ser atentido por vez.");

        jLabel4.setText("Quantidade de caixas:");

        txtQuantCaixa.setText("5");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("* Defina as configurações do supermercado:");

        jLabel6.setText("* (1 - 15)");

        jLabel8.setText("Quantidade de clientes:");

        txtQuantClientes.setText("20");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("* Configurações adicionais:");

        cbDeadlock.setText("Simular deadLock");
        cbDeadlock.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDeadlockItemStateChanged(evt);
            }
        });
        cbDeadlock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbDeadlockMouseClicked(evt);
            }
        });

        jLabel9.setText("Tempo de funcionamento:");

        txtTempoFuncionamento.setText("15");

        jLabel11.setText("* segundos");

        cbInanicao.setText("Simular inanição");
        cbInanicao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbInanicaoItemStateChanged(evt);
            }
        });
        cbInanicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbInanicaoMouseClicked(evt);
            }
        });

        jLabel10.setText("* Caixa será bloqueado por outro caixa");

        jLabel12.setText("* Clientes não serão atentidos por um caixa");

        jLabel13.setText("Quantidade de troco:");

        jLabel14.setText("Chance de precisar de troco");

        txtQuantTroco.setText("5");

        txtChanceTroco.setText("50");

        jLabel15.setText("* unidade");

        jLabel16.setText("* (0 - 100)");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Problema:");

        jLabel19.setText("Intervalo de tempo de compra:");

        txtTempoCompra.setText("3");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Supermercado:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Caixa:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Cliente:");

        btbIniciar.setText("Iniciar");
        btbIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbIniciarActionPerformed(evt);
            }
        });

        cbViolarExclusaoMutua.setText("Violar exclusão mútua");
        cbViolarExclusaoMutua.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbViolarExclusaoMutuaItemStateChanged(evt);
            }
        });
        cbViolarExclusaoMutua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbViolarExclusaoMutuaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(21, 21, 21)
                                .addComponent(txtChanceTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel17)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtQuantClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTempoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtQuantTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel15))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtQuantCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(4, 4, 4)
                                                .addComponent(jLabel6))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(27, 27, 27)
                                        .addComponent(txtTempoFuncionamento, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel4))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cbInanicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbDeadlock))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel10)))
                                    .addComponent(cbViolarExclusaoMutua))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(btbIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbDeadlock)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbInanicao)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbViolarExclusaoMutua))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtTempoFuncionamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtQuantCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtQuantTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtQuantClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtTempoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtChanceTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))))
                .addGap(18, 18, 18)
                .addComponent(btbIniciar)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbDeadlockItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDeadlockItemStateChanged

    }//GEN-LAST:event_cbDeadlockItemStateChanged

    private void cbInanicaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbInanicaoItemStateChanged

    }//GEN-LAST:event_cbInanicaoItemStateChanged

    private void cbDeadlockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDeadlockMouseClicked
        if (cbDeadlock.isSelected()) {
            deadlock = true;
            JOptionPane.showMessageDialog(this, "Deadlock ativado");
            txtTempoFuncionamento.setText("10");
            txtQuantCaixa.setText("3");
            txtQuantTroco.setText("0");
            txtQuantClientes.setText("6");
            txtChanceTroco.setText("100");
        } else {
            deadlock = false;
            JOptionPane.showMessageDialog(this, "Deadlock desativado");
        }
    }//GEN-LAST:event_cbDeadlockMouseClicked

    private void cbInanicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbInanicaoMouseClicked
        if (cbInanicao.isSelected()) {
            inanicao = true;
            JOptionPane.showMessageDialog(this, "Inanição ativada");
            txtTempoFuncionamento.setText("15");
            txtQuantCaixa.setText("5");
            txtQuantTroco.setText("5");
            txtQuantClientes.setText("20");
            txtTempoCompra.setText("3");
        } else {
            inanicao = true;
            JOptionPane.showMessageDialog(this, "Inanição desativada");
        }
    }//GEN-LAST:event_cbInanicaoMouseClicked

    private void btbIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbIniciarActionPerformed
        //validar valores informados
        int quantCaixas = 0, quantClientes = 0, tempoFuncionamento = 0, quantTroco = 0, chancePrecisarTroco = 0, tempoCompra = 0;

        try {
            quantCaixas = Integer.parseInt(txtQuantCaixa.getText().trim());
            quantClientes = Integer.parseInt(txtQuantClientes.getText().trim());
            tempoFuncionamento = Integer.parseInt(txtTempoFuncionamento.getText().trim());
            quantTroco = Integer.parseInt(txtQuantTroco.getText().trim());
            chancePrecisarTroco = Integer.parseInt(txtChanceTroco.getText().trim());
            tempoCompra = Integer.parseInt(txtTempoCompra.getText().trim());
            
            if ((quantCaixas < 1 || quantCaixas > 15) || (quantClientes < 0) || (tempoFuncionamento < 0) || (quantTroco < 0) || (chancePrecisarTroco < 0 || quantCaixas > 100) || tempoCompra < 0) {
                JOptionPane.showMessageDialog(null, "Um ou mais campos com valores inválidos! Verifique se todos possuem campos numéricos de acordo com os requisitos.");
            } 
            else {
                //iniciar aplicação
                System.out.println("\n---------- Supermercado abriu ----------\n");

                Supermercado supermercado = new Supermercado(tempoFuncionamento);

                List<Thread> threadsCaixa = new ArrayList<>();
                List<Caixa> listaCaixas = new ArrayList<>();
                List<Cliente> listaClientes = new ArrayList<>();

                //criar e dar start nos caixas
                for (int i = 0; i < quantCaixas; i++) {
                    Caixa caixa = new Caixa(i, quantTroco, supermercado);
                    Thread threadCaixa = new Thread(caixa);
                    threadsCaixa.add(threadCaixa);
                    listaCaixas.add(caixa);

                    threadCaixa.start();
                    System.out.println(CoresMensagens.corVerde + "Caixa " + caixa.getId() + " está aberto!");
                }

                supermercado.setListaCaixas(listaCaixas);

                //criar clientes
                Random random = new Random();
                for (int i = 0; i < quantClientes; i++) {
                    Cliente cliente = null;
                    int clienteTempoCompra = random.nextInt(tempoCompra) + 1; //tempo de compra varia de 1 até o valor informado
                    boolean clientePrecisaTroco = random.nextDouble() < (chancePrecisarTroco / 100); //gerar um n° double pra transformar a chance de n° para boolean
                    cliente = new Cliente(i, clienteTempoCompra, clientePrecisaTroco);  

                    listaClientes.add(cliente); 
                }

                //há duas formas de distribuir clientes nos caixas 
                if(!inanicao){
                    //clietes são distribuídos proporcionalmente entre os caixas
                    int clientesPorCaixa = quantClientes / quantCaixas;
                    int indiceCliente = 0;
                    Collections.shuffle(listaClientes); 

                    for (Caixa caixa : listaCaixas) {
                        for (int i = 0; i < clientesPorCaixa; i++) {
                            if (indiceCliente < listaClientes.size()) {
                                caixa.adicionarClienteNaFila(listaClientes.get(indiceCliente));
                                indiceCliente++;
                            }
                        }
                    }

                    //adicionar os clientes que sobraram
                    while (indiceCliente < listaClientes.size()) {
                        for (Caixa caixa : listaCaixas) {
                            if (indiceCliente < listaClientes.size()) {
                                caixa.adicionarClienteNaFila(listaClientes.get(indiceCliente));
                                indiceCliente++;
                            }
                        }
                    }
                }
                else{
                    //distribuir clientes aleatoriamente entre os caixas, isso pode fazer com que um caixa atenta muitos clientes enquanto outros fiquem vazios
                    for (int i = 0; i < quantClientes; i++) {
                        int caixaEscolhido = random.nextInt(quantCaixas);
                        listaCaixas.get(caixaEscolhido).adicionarClienteNaFila(listaClientes.get(i));
                    }
                }

                //supermercado "dorme" de acordo com o tempo de funcionamento informado
                //OBS: as threads de caixa continuam funcionando mesmo com a thread main dormindo
                try {
                    Thread.sleep(tempoFuncionamento * 1000);
                    supermercado.fecharSupermercado();
                    for (int i = 0; i < quantCaixas; i++) {
                        System.out.println(CoresMensagens.corVerde + "Caixa " + listaCaixas.get(i).getId() + " está fechado!");
                    }

                    System.out.println("\n---------- Supermercado fechou ----------");

                    System.out.println("\nEsperando caixas terimarem de atender possíveis clientes...\n");
                    Thread.sleep(tempoCompra * 1000);
                } 
                catch (InterruptedException ex) {
                    JOptionPane.showMessageDialog(null, CoresMensagens.corVermelho + "Erro no funcionamento do supermercado.");
                }

                //mostrar se houve clientes que não foram atentidos na fila dos caixas
                int clientesNaoAtendidos = 0;
                for (Caixa caixa : listaCaixas) {
                    List<Cliente> filaClientes = caixa.getFilaClientes();
                    if (!filaClientes.isEmpty()) {
                        clientesNaoAtendidos++;
                    }
                }

                if (clientesNaoAtendidos == 0) {
                    System.out.println( CoresMensagens.corVerde +"\nTodos os clientes foram atendidos");
                } 
                else {
                    System.out.println(CoresMensagens.corVermelho + "\nAlguns clientes não foram atendidos:");
                    for (Caixa ca : listaCaixas) {
                        System.out.println(ca.toString());
                    }
                }
            }
        } 
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Um ou mais campos inválidos! Verifique se todos possuem valor númerico");
        }
    }//GEN-LAST:event_btbIniciarActionPerformed

    private void cbViolarExclusaoMutuaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbViolarExclusaoMutuaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbViolarExclusaoMutuaItemStateChanged

    private void cbViolarExclusaoMutuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbViolarExclusaoMutuaMouseClicked
        if (cbViolarExclusaoMutua.isSelected()) {
            violarExclusaoMutua = true;
            JOptionPane.showMessageDialog(this, "Violar exclusão mútua ativada");
            txtTempoFuncionamento.setText("5");
            txtQuantCaixa.setText("1");
            txtQuantClientes.setText("5");
            txtTempoCompra.setText("3");
        } else {
            violarExclusaoMutua = false;
            JOptionPane.showMessageDialog(this, "Violar exclusão mútua desativada");
        }
    }//GEN-LAST:event_cbViolarExclusaoMutuaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupermercadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupermercadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupermercadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupermercadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupermercadoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbIniciar;
    private javax.swing.JCheckBox cbDeadlock;
    private javax.swing.JCheckBox cbInanicao;
    private javax.swing.JCheckBox cbViolarExclusaoMutua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtChanceTroco;
    private javax.swing.JTextField txtQuantCaixa;
    private javax.swing.JTextField txtQuantClientes;
    private javax.swing.JTextField txtQuantTroco;
    private javax.swing.JTextField txtTempoCompra;
    private javax.swing.JTextField txtTempoFuncionamento;
    // End of variables declaration//GEN-END:variables
}
