package supermercadoconcorrencia;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;

public class Supermercado extends javax.swing.JFrame {

    public static String corVermelho = "\u001B[31m";
    public static String corVerde = "\u001B[32m";
    public static String corAzul = "\u001B[34m";
    
    public Supermercado() {
        initComponents();
        
        /*
        String mensagem = "Sua mensagem aqui";
        String vermelho = "\u001B[31m";
        String azul = "\u001B[34m";
        System.out.println(vermelho + mensagem);
        System.out.println(azul + mensagem);
        System.out.println(corVerde + mensagem);
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtQuantCaixa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtQuantClientes = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbDeadlock = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        txtTempoFuncionamento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbInanicao = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtQuantTroco = new javax.swing.JTextField();
        txtChanceTroco = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTempoCompra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Supermercado com concorrência");

        jLabel2.setText("Um supermercado possui alguns caixas que devem atender vários clientes, mas em cada caixa, só um cliente pode ser atentido por vez.");

        jLabel4.setText("Quantidade de caixas:");

        txtQuantCaixa.setText("5");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("* Defina as configurações do supermercado:");

        jLabel6.setText("* (1 - 15)");

        jLabel8.setText("Quantidade de clientes:");

        txtQuantClientes.setText("15");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("* Configurações adicionais:");

        cbDeadlock.setText("Forçar DeadLock");
        cbDeadlock.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDeadlockItemStateChanged(evt);
            }
        });

        jLabel9.setText("Tempo de funcionamento:");

        txtTempoFuncionamento.setText("20");

        jLabel11.setText("* segundos");

        cbInanicao.setText("Forçar inanição");
        cbInanicao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbInanicaoItemStateChanged(evt);
            }
        });

        jLabel10.setText("* Implementar sistema de troco");

        jLabel12.setText("* Clientes não serão atentidos pelo caixa");

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        jLabel13.setText("Quantidade de troco:");

        jLabel14.setText("Chance de precisar de troco");

        txtQuantTroco.setText("10");

        txtChanceTroco.setText("0");

        jLabel15.setText("* unidade");

        jLabel16.setText("* (0 - 100)");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Problema:");

        jLabel19.setText("Tempo de compra:");

        txtTempoCompra.setText("3");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Supermercado:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Caixa:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Cliente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtTempoFuncionamento, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel11))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtChanceTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel16))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(35, 35, 35)
                                                .addComponent(txtQuantClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addGap(59, 59, 59)
                                                .addComponent(txtTempoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel17))
                                        .addGap(58, 58, 58)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(cbInanicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(cbDeadlock))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel10))))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(43, 43, 43)
                                        .addComponent(txtQuantCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(159, 159, 159)
                                        .addComponent(txtQuantTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbDeadlock)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbInanicao)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtTempoFuncionamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtQuantCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtQuantTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtQuantClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtTempoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtChanceTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(27, 27, 27)))
                .addComponent(btnIniciar)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        
        //validar valores informados
        int quantCaixas = 0, quantClientes = 0, tempoFuncionamento = 0, quantTroco = 0, chancePrecisarTroco = 0, tempoCompra = 0;
        
        try {
            quantCaixas = Integer.parseInt(txtQuantCaixa.getText().trim());
            quantClientes = Integer.parseInt(txtQuantClientes.getText().trim());
            tempoFuncionamento = Integer.parseInt(txtTempoFuncionamento.getText().trim());
            quantTroco = Integer.parseInt(txtQuantTroco.getText().trim());
            chancePrecisarTroco = Integer.parseInt(txtChanceTroco.getText().trim());
            tempoCompra = Integer.parseInt(txtTempoCompra.getText().trim());
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Um ou mais campos inválidos! Verifique se todos possuem valor númerico");
        }
        
        if((quantCaixas < 1 || quantCaixas > 15) || (quantClientes < 0) || (tempoFuncionamento < 0) || (quantTroco < 0) || (chancePrecisarTroco < 0 || quantCaixas > 100) || tempoCompra < 0){
            JOptionPane.showMessageDialog(null, "Um ou mais campos com valores inválidos! Verifique se todos possuem campos numéricos de acordo com os requisitos.");
        }
        else{
            //iniciar aplicação
            System.out.println("---------- Supermercado abriu ----------\n");
            
            //inicializar arrays para guardar os caixas
            List<Thread> threadsCaixa = new ArrayList<>();
            List<Caixa> listaCaixas = new ArrayList<>();
            
            //criar e dar start nos caixas
            for (int i = 0; i < quantCaixas; i++) {
                Caixa caixa = new Caixa(i, quantTroco);
                Thread threadCaixa = new Thread(caixa);
                threadsCaixa.add(threadCaixa);
                threadCaixa.start();
                listaCaixas.add(caixa);
                
                System.out.println(corVerde + "Caixa " + caixa.getId() + " está aberto!");
            }
            
            //criar clientes
            Random random = new Random();
            for (int i = 1; i <= quantClientes; i++) {
                Cliente cliente = null;
                
                //double percentual = (chancePrecisarTroco/100);
                //cliente = new Cliente(i, tempoCompra, random.nextDouble() < percentual); 
                
                int clienteTempocompra = random.nextInt(tempoCompra) + 1;
                boolean clientePrecisaTroco = random.nextDouble() < (chancePrecisarTroco/100); //gerar um n° double pra transformar a chance de n° para boolean
                cliente = new Cliente(i, clienteTempocompra, clientePrecisaTroco);  // mudar tempo de compra 
                
                //um cliente já entra na fila do caixa ao ser criado
                int caixaEscolhido = random.nextInt(quantCaixas);
                listaCaixas.get(caixaEscolhido).adicionarClienteNaFila(cliente);
            }
            
            //supermercado dorme de acordo com o tempo de funcionamento informado
            //OBS: as threads de caixa comtinuam funcionando mesmo com o a thread main dormindo
            try {
                Thread.sleep(tempoFuncionamento*1000);
            } catch (InterruptedException ex) {
                JOptionPane.showMessageDialog(null, "Erro no funcionamento do supermercado.");
            }
            
            System.out.println("\n---------- Supermercado fechou ----------\n");
            
            //interromper as threads após o tempo de simulação
            for (Thread thread : threadsCaixa) {
                thread.interrupt();
            }
            
            //mostrar se houve clientes que não foram atetidos na fila dor caixas
            //.......
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    /*public static void outraFuncao() {
        System.out.println("Início da outra função");
        // Lógica da outra função aqui
        System.out.println("Fim da outra função");
    }*/
    
    private void cbDeadlockItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDeadlockItemStateChanged
        if(cbDeadlock.isSelected()){
            JOptionPane.showMessageDialog(this, "Deadlock ativado");
            txtChanceTroco.setText("100");
            txtQuantTroco.setText("1");
            txtQuantCaixa.setText("3");
            txtQuantClientes.setText("6");
        }
        else{
            JOptionPane.showMessageDialog(this, "Deadlock desativado");
            txtChanceTroco.setText("10");
            txtQuantCaixa.setText("5");
            txtQuantClientes.setText("15");
            txtTempoFuncionamento.setText("20");
        }
    }//GEN-LAST:event_cbDeadlockItemStateChanged

    private void cbInanicaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbInanicaoItemStateChanged
        if(cbInanicao.isSelected()){
            JOptionPane.showMessageDialog(this, "Inanição ativada");
            txtQuantCaixa.setText("3");
            txtQuantClientes.setText("100");
            txtTempoFuncionamento.setText("10");
        }
        else{
            JOptionPane.showMessageDialog(this, "Inanição desativada");
            txtQuantCaixa.setText("5");
            txtQuantClientes.setText("15");
            txtTempoFuncionamento.setText("20");
        }
    }//GEN-LAST:event_cbInanicaoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supermercado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JCheckBox cbDeadlock;
    private javax.swing.JCheckBox cbInanicao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtChanceTroco;
    private javax.swing.JTextField txtQuantCaixa;
    private javax.swing.JTextField txtQuantClientes;
    private javax.swing.JTextField txtQuantTroco;
    private javax.swing.JTextField txtTempoCompra;
    private javax.swing.JTextField txtTempoFuncionamento;
    // End of variables declaration//GEN-END:variables
}
